apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: __IMAGE__               # Jenkins will replace this dynamically
        imagePullPolicy: Always        # Always pull the new image
        ports:
        - containerPort: 8000

        
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: expense-tracker-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: expense-tracker
#   template:
#     metadata:
#       labels:
#         app: expense-tracker
#     spec:
#       containers:
#       - name: expense-tracker
#         image: khushiacr2025.azurecr.io/expense-tracker-app:latest
#         ports:
#         - containerPort: 8000
