apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
  labels:
    created-by: jenkins-pipeline
spec:
  selector:
    app: expense-tracker
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000